# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
# image: python:latest

variables:
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
  CACHE_DIR: "$CI_PROJECT_DIR/protobuf3"

cache:
  paths:
    - protobuf3/
    - protobuf-all-3.5.1.tar.gz

before_script:
  
stages:
  - build

job1:
  stage: build
  script:
    - export
    - build.sh
    - export
    - echo "Done."
  artifacts:
    paths:
      - bin/
  only:
    - tags

    
