# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
# image: python:latest

variables:
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
  CACHE_DIR: "$CI_PROJECT_DIR/protobuf3"

cache:
  paths:
    - protobuf3/
    - protobuf-all-3.5.1.tar.gz
    - bin/

before_script:
  - apt-get -y update
  - apt-get install -y cmake
  
stages:
  - build

job1:
  stage: build
  script:
    - ./build.sh
    - echo "Done."
  artifacts:
    paths:
      - bin/pbstru
    expire_in: 1 week
  only:
    - master

    
