/* This file is generated by [pbstru](https://gitlab.zte.com.cn/10016632/pbstru) */
/* version: 3.1-142-b231b8e */
/* DO NOT modify it manually. */

#include "hello.h"

/* lint -save -e701 -e647 */

void constru_message_Hello_191230025720(st_hello* var_Hello) {
    var_Hello->var_id = 0;
    var_Hello->var_flt = 0.0;
    var_Hello->var_str.length = 0;
    var_Hello->var_str.data = NULL;
    var_Hello->var_opt = 0;
    var_Hello->has_opt = FALSE;
}

void clear_message_Hello_191230025720(st_hello* var_Hello) {
    var_Hello->var_id = 0;
    var_Hello->var_flt = 0.0;
    var_Hello->var_str.length = 0;
    var_Hello->var_str.data = NULL;
    if(TRUE == var_Hello->has_opt) {
        var_Hello->var_opt = 0;
    }
    var_Hello->has_opt = FALSE;
}

void _clear_message_Hello_len_191230025720(st_hello* var_Hello) {
    var_Hello->_message_length = 0;
}

size_t _internal_encode_message_Hello_191230025720(st_hello* var_Hello, BYTE* buf) {
    size_t offset = 0;

    /* tag:1 type:int32 */
    encode_tag_byte_191230025720(buf, 1, WIRE_TYPE_VARINT, &offset);
    encode_varint(var_Hello->var_id, buf, &offset);

    /* tag:2 type:float */
    encode_tag_byte_191230025720(buf, 2, WIRE_TYPE_FIX32, &offset);
    if(NULL != buf) {
        *((float *)(buf + offset)) = var_Hello->var_flt;
    }
    offset += sizeof(float);

    /* tag:3 type:string */
    encode_tag_byte_191230025720(buf, 3, WIRE_TYPE_LENGTH_DELIMITED, &offset);
    encode_varint(var_Hello->var_str.length, buf, &offset);
    if (NULL != buf && var_Hello->var_str.length > 0) {
        memcpy(buf + offset, (unsigned char *)var_Hello->var_str.data, var_Hello->var_str.length);
    }
    offset += var_Hello->var_str.length;

    if(var_Hello->has_opt) {
        /* tag:4 type:int32 */
        encode_tag_byte_191230025720(buf, 4, WIRE_TYPE_VARINT, &offset);
        encode_varint(var_Hello->var_opt, buf, &offset);
    }

    return offset;
}

size_t encode_message_Hello_safe_191230025720(st_hello* var_Hello, BYTE* buf, size_t buf_size) {
    _clear_message_Hello_len_191230025720(var_Hello); 

    if (_internal_encode_message_Hello_191230025720(var_Hello, NULL) > buf_size) {
        return 0;
    }
    return _internal_encode_message_Hello_191230025720(var_Hello, buf);
}


BOOL decode_message_Hello_191230025720(BYTE* buf, const size_t buf_len, st_hello* var_Hello) {
    size_t offset = 0;
    WORD field_num;
    BYTE wire_type;

    clear_message_Hello(var_Hello);
    if(0 == buf_len) {
        return TRUE;
    }

    for(;offset < buf_len;) {
        if(FALSE == parse_tag_byte_191230025720(buf+offset, buf_len-offset, &field_num, &wire_type, &offset)) {
            return FALSE;
        }
        switch(field_num) {
        case 1:  /* type:int32 */
            decode_varint(buf+offset, buf_len-offset, &(var_Hello->var_id), &offset);
            break;

        case 2:  /* type:float */
            if((offset + sizeof(float)) > buf_len) {
                return FALSE;
            }
            var_Hello->var_flt = *((float *)(buf + offset));
            offset += sizeof(float);
            break;

        case 3:  /* type:string */
            decode_varint(buf+offset, buf_len-offset, &(var_Hello->var_str.length), &offset);
            if((offset + var_Hello->var_str.length) > buf_len) {
                return FALSE;
            }
            var_Hello->var_str.data = (char *)(buf + offset);
            offset += var_Hello->var_str.length;
            break;

        case 4:  /* type:int32 */
            decode_varint(buf+offset, buf_len-offset, &(var_Hello->var_opt), &offset);
            var_Hello->has_opt = TRUE;
            break;

        default:
            deal_unknown_field(wire_type, buf+offset, buf_len-offset, &offset);
            break;
        }
    }
    return TRUE;
}

/* lint -restore */
/* end of file */

