/* This file is generated by [pbstru](https://gitlab.zte.com.cn/10016632/pbstru) */
/* version: 3.1-142-b231b8e */
/* DO NOT modify it manually. */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "pbstru_comm.h"

/*
message Hello {
  required int32 id = 1;
  required float flt = 2;
  required string str = 3;
  optional int32 opt = 4;
}
*/

typedef struct _st_hello {
    long var_id;  /* tag:1 */
    float var_flt;  /* tag:2 */
    ps_string var_str;  /* tag:3 */
    BOOL has_opt;
    long var_opt;  /* tag:4 */

    size_t _message_length;  // The length of this message, DO NOT set it manually. 
                            // Setting and Using at _internal_encode_message_xxx().
} st_hello;

/* construct msg, DO NOT use it high frequency. */
#define constru_message_Hello(msg) constru_message_Hello_191230025720(msg)
void constru_message_Hello_191230025720(st_hello *msg);


/* clear and reuse msg */
#define clear_message_Hello(msg) clear_message_Hello_191230025720(msg)
void clear_message_Hello_191230025720(st_hello *msg);

void _clear_message_Hello_len_191230025720(st_hello *msg);

#define encode_message_Hello_safe(msg, buf, buf_size) encode_message_Hello_safe_191230025720((msg), (buf), (buf_size))
size_t encode_message_Hello_safe_191230025720(st_hello* msg, BYTE* buf, size_t buf_size);

size_t _internal_encode_message_Hello_191230025720(st_hello* msg, BYTE* buf);

#define decode_message_Hello(buf, buf_len, msg) decode_message_Hello_191230025720((buf), (buf_len), (msg))
BOOL decode_message_Hello_191230025720(BYTE* buf, size_t buf_len, st_hello* msg);

#ifdef __cplusplus
}
#endif

/* end of file */

