/* This file is generated by [pbstru](https://gitlab.zte.com.cn/10016632/pbstru) */
/* version: 3.1-109-7eabe92 */
/* DO NOT modify it manually. */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "pbstru_comm.h"

/*
message Hello {
  required int32 id = 1;
  required float flt = 2;
  required string str = 3;
  optional int32 opt = 4;
}
*/

typedef struct _st_hello {
[pbstru.cpp:574] Unknown field type:int32, Please contact the author.
[pbstru.cpp:574] Unknown field type:float, Please contact the author.
    ps_string var_str;  /* tag:3 */
    BOOL has_opt;
[pbstru.cpp:574] Unknown field type:int32, Please contact the author.

    size_t _message_length;  // The length of this message, DO NOT set it manually. 
                            // Setting and Using at _internal_encode_message_xxx().
} st_hello;

/* construct msg, DO NOT use it high frequency. */
#define constru_message_Hello(msg) constru_message_Hello_191115023335(msg)
void constru_message_Hello_191115023335(st_hello *msg);


/* clear and reuse msg */
#define clear_message_Hello(msg) clear_message_Hello_191115023335(msg)
void clear_message_Hello_191115023335(st_hello *msg);

void _clear_message_Hello_len_191115023335(st_hello *msg);

#define encode_message_Hello_safe(msg, buf, buf_size) encode_message_Hello_safe_191115023335((msg), (buf), (buf_size))
size_t encode_message_Hello_safe_191115023335(st_hello* msg, BYTE* buf, size_t buf_size);

size_t _internal_encode_message_Hello_191115023335(st_hello* msg, BYTE* buf);

#define decode_message_Hello(buf, buf_len, msg) decode_message_Hello_191115023335((buf), (buf_len), (msg))
BOOL decode_message_Hello_191115023335(BYTE* buf, size_t buf_len, st_hello* msg);

#ifdef __cplusplus
}
#endif

/* end of file */

