version: '1.0'
name: pipeline-20240909
displayName: pipeline-20240909
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-e7415c20
    displayName: compile
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '8.4'
        commands:
          - apt-get update -y && apt-get install -y gcc g++ cmake autoconf libtool
          - ./build.sh
          - ls -F
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: pbstru
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_gcc
  - name: stage-9192e11a
    displayName: release
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: pbstru
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
